<a href="https://colab.research.google.com/github/akshatsharma-x/ML/blob/main/Lab_4b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:
import os
os.listdir('/content/drive/MyDrive/')


['Contacts (3).vcf',
 'Akshat Sharma (1).vcf',
 '2017-04-04_11.46.04.jpg',
 '2017-04-04_11.16.28.jpg',
 'Photo Collage_1484053271333.png',
 'Photo Collage_1484191896103.png',
 'Photo Collage_1485592182546.png',
 'IMG-20170318-WA0004.jpg',
 'IMG-20170403-WA0000.jpg',
 'IMG-20170403-WA0001.jpg',
 '2017-03-22 14.57.50.jpg',
 'IMG-20170318-WA0003.jpg',
 'IMG-20170308-WA0007.jpg',
 'IMG-20170318-WA0002.jpg',
 '2017-03-18 15.29.37.jpg',
 'IMG-20170308-WA0004.jpg',
 'IMG-20170308-WA0002.jpg',
 'IMG-20170308-WA0001.jpg',
 'IMG-20170226-WA0001.jpg',
 'IMG-20170226-WA0000.jpg',
 'IMG-20170108-WA0001.jpg',
 'IMG-20170108-WA0001-1.jpg',
 'B612_20170404_212744.jpg',
 'B612_20170404_213045.jpg',
 'B612_20170404_212804.jpg',
 'B612_20170404_213055.jpg',
 'B612_20161231_221941.jpg',
 'B612_20161231_222115.jpg',
 'B612_20161231_222730.jpg',
 'B612_20161231_221931.jpg',
 'B612_20161231_210016.jpg',
 'B612_20161231_204758.jpg',
 'B612_20161231_204536.jpg',
 'B612_20161231_205318.jpg',
 'B612_20161231_204

In [19]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Iris.csv')
df.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
import pandas as pd
import numpy as np

# from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score,
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [21]:
import pandas as pd

columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

df = pd.read_csv(r'/content/drive/MyDrive/Iris.csv', header=0)

df = df.drop(columns=['Id'])

df.columns = columns

for col in ["sepal_length", "sepal_width", "petal_length", "petal_width"]:
    df[col] = pd.to_numeric(df[col])

In [22]:
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [23]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [24]:
X_lr = df[["sepal_length", "sepal_width", "petal_width"]]
y_lr = df["petal_length"]

In [25]:
X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(
    X_lr, y_lr, test_size=0.2, random_state=42)

In [26]:
lr_model = LinearRegression()

In [27]:
lr_model.fit(X_train_lr, y_train_lr)
y_pred_lr = lr_model.predict(X_test_lr)

In [28]:
print("LINEAR REGRESSION EVALUATION")
print("Mean Squared Error:", mean_squared_error(y_test_lr, y_pred_lr))
print("Mean Absolute Error:", mean_absolute_error(y_test_lr, y_pred_lr))
print("R2 Score:", r2_score(y_test_lr, y_pred_lr))

LINEAR REGRESSION EVALUATION
Mean Squared Error: 0.12991981605759947
Mean Absolute Error: 0.2606173239288886
R2 Score: 0.9603587427485161


In [29]:
df = pd.read_csv(r'/content/drive/MyDrive/Iris.csv')

In [30]:
df["Species"] = df["Species"].replace({
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
})

/tmp/ipython-input-1910832043.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Species"] = df["Species"].replace({


In [31]:
X_lr = df[["SepalLengthCm", "SepalWidthCm", "PetalWidthCm"]]
y_lr = df["PetalLengthCm"]

In [32]:
y_pred_lr = lr_model.predict(X_test_lr)

In [33]:
print("LINEAR REGRESSION EVALUATION")
print("Mean Squared Error:", mean_squared_error(y_test_lr, y_pred_lr))
print("Mean Absolute Error:", mean_absolute_error(y_test_lr, y_pred_lr))
print("R2 Score:", r2_score(y_test_lr, y_pred_lr))

LINEAR REGRESSION EVALUATION
Mean Squared Error: 0.12991981605759947
Mean Absolute Error: 0.2606173239288886
R2 Score: 0.9603587427485161


In [37]:
X = df.drop(columns=["Species"])
y = df["Species"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

log_model = LogisticRegression(max_iter=200)
log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print("\nLOGISTIC REGRESSION EVALUATION")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log))


LOGISTIC REGRESSION EVALUATION
Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [36]:
X = df.drop("Species", axis=1)
y = df["Species"]